/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDemo {
    }
    interface AppRoot {
    }
    interface DndCalendar {
        /**
          * Props and State
         */
        "startDate": Date;
    }
    interface DndSlides {
    }
}
declare global {
    interface HTMLAppDemoElement extends Components.AppDemo, HTMLStencilElement {
    }
    var HTMLAppDemoElement: {
        prototype: HTMLAppDemoElement;
        new (): HTMLAppDemoElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDndCalendarElement extends Components.DndCalendar, HTMLStencilElement {
    }
    var HTMLDndCalendarElement: {
        prototype: HTMLDndCalendarElement;
        new (): HTMLDndCalendarElement;
    };
    interface HTMLDndSlidesElement extends Components.DndSlides, HTMLStencilElement {
    }
    var HTMLDndSlidesElement: {
        prototype: HTMLDndSlidesElement;
        new (): HTMLDndSlidesElement;
    };
    interface HTMLElementTagNameMap {
        "app-demo": HTMLAppDemoElement;
        "app-root": HTMLAppRootElement;
        "dnd-calendar": HTMLDndCalendarElement;
        "dnd-slides": HTMLDndSlidesElement;
    }
}
declare namespace LocalJSX {
    interface AppDemo {
    }
    interface AppRoot {
    }
    interface DndCalendar {
        "onDateSelected"?: (event: CustomEvent<Date>) => void;
        /**
          * Props and State
         */
        "startDate"?: Date;
    }
    interface DndSlides {
    }
    interface IntrinsicElements {
        "app-demo": AppDemo;
        "app-root": AppRoot;
        "dnd-calendar": DndCalendar;
        "dnd-slides": DndSlides;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-demo": LocalJSX.AppDemo & JSXBase.HTMLAttributes<HTMLAppDemoElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "dnd-calendar": LocalJSX.DndCalendar & JSXBase.HTMLAttributes<HTMLDndCalendarElement>;
            "dnd-slides": LocalJSX.DndSlides & JSXBase.HTMLAttributes<HTMLDndSlidesElement>;
        }
    }
}
