/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDemo {
    }
    interface AppRoot {
    }
    interface DndCalendar {
        "columnheader": 'none' | 'ariaLabel' | 'abbr' | 'text';
        "contrast": 'none' | 'arrows' | 'all';
        "focusDate": () => Promise<void>;
        "focusModel": 'cell' | 'button' | 'dual';
        "selectedDay": Date;
        /**
          * Props and State
         */
        "startDate": Date;
    }
    interface DndDatepicker {
        "columnheader": 'none' | 'ariaLabel' | 'abbr' | 'text';
        "contrast": 'none' | 'arrows' | 'all';
        "focusModel": 'cell' | 'button' | 'dual';
        "showInput": boolean;
        /**
          * Props and State
         */
        "startDate": Date;
    }
    interface DndMiniGrid {
        /**
          * Props and State
         */
        "cellFocus": boolean;
    }
    interface DndSlides {
    }
}
declare global {
    interface HTMLAppDemoElement extends Components.AppDemo, HTMLStencilElement {
    }
    var HTMLAppDemoElement: {
        prototype: HTMLAppDemoElement;
        new (): HTMLAppDemoElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDndCalendarElement extends Components.DndCalendar, HTMLStencilElement {
    }
    var HTMLDndCalendarElement: {
        prototype: HTMLDndCalendarElement;
        new (): HTMLDndCalendarElement;
    };
    interface HTMLDndDatepickerElement extends Components.DndDatepicker, HTMLStencilElement {
    }
    var HTMLDndDatepickerElement: {
        prototype: HTMLDndDatepickerElement;
        new (): HTMLDndDatepickerElement;
    };
    interface HTMLDndMiniGridElement extends Components.DndMiniGrid, HTMLStencilElement {
    }
    var HTMLDndMiniGridElement: {
        prototype: HTMLDndMiniGridElement;
        new (): HTMLDndMiniGridElement;
    };
    interface HTMLDndSlidesElement extends Components.DndSlides, HTMLStencilElement {
    }
    var HTMLDndSlidesElement: {
        prototype: HTMLDndSlidesElement;
        new (): HTMLDndSlidesElement;
    };
    interface HTMLElementTagNameMap {
        "app-demo": HTMLAppDemoElement;
        "app-root": HTMLAppRootElement;
        "dnd-calendar": HTMLDndCalendarElement;
        "dnd-datepicker": HTMLDndDatepickerElement;
        "dnd-mini-grid": HTMLDndMiniGridElement;
        "dnd-slides": HTMLDndSlidesElement;
    }
}
declare namespace LocalJSX {
    interface AppDemo {
    }
    interface AppRoot {
    }
    interface DndCalendar {
        "columnheader"?: 'none' | 'ariaLabel' | 'abbr' | 'text';
        "contrast"?: 'none' | 'arrows' | 'all';
        "focusModel"?: 'cell' | 'button' | 'dual';
        "onDateSelected"?: (event: CustomEvent<Date>) => void;
        "selectedDay"?: Date;
        /**
          * Props and State
         */
        "startDate"?: Date;
    }
    interface DndDatepicker {
        "columnheader"?: 'none' | 'ariaLabel' | 'abbr' | 'text';
        "contrast"?: 'none' | 'arrows' | 'all';
        "focusModel"?: 'cell' | 'button' | 'dual';
        "showInput"?: boolean;
        /**
          * Props and State
         */
        "startDate"?: Date;
    }
    interface DndMiniGrid {
        /**
          * Props and State
         */
        "cellFocus"?: boolean;
    }
    interface DndSlides {
    }
    interface IntrinsicElements {
        "app-demo": AppDemo;
        "app-root": AppRoot;
        "dnd-calendar": DndCalendar;
        "dnd-datepicker": DndDatepicker;
        "dnd-mini-grid": DndMiniGrid;
        "dnd-slides": DndSlides;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-demo": LocalJSX.AppDemo & JSXBase.HTMLAttributes<HTMLAppDemoElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "dnd-calendar": LocalJSX.DndCalendar & JSXBase.HTMLAttributes<HTMLDndCalendarElement>;
            "dnd-datepicker": LocalJSX.DndDatepicker & JSXBase.HTMLAttributes<HTMLDndDatepickerElement>;
            "dnd-mini-grid": LocalJSX.DndMiniGrid & JSXBase.HTMLAttributes<HTMLDndMiniGridElement>;
            "dnd-slides": LocalJSX.DndSlides & JSXBase.HTMLAttributes<HTMLDndSlidesElement>;
        }
    }
}
